config-version: 5

# Should we prevent messages from being reported?
# Leave as yes until you have a different plugin stripping those.
strip-signature: true

# Only for 1.19 servers, read server log first.
no-warning: false

# Do not touch this!
first-run: true