config-version: 7

# Should we prevent messages from being reported?
# Leave as true unless you have a different plugin stripping those.
strip-signature: true

dont-send-header: true

# Do not touch this!
first-run: true