name: Platform Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: HFTnFHKn
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH }}

          curseforge-id: 663152
          curseforge-token: ${{ secrets.CURSE }}

          files: build/libs/AntiPopup-*.jar
          files-primary: ""
          files-secondary: ""

          game-versions: |
            1.19.2
            1.19.1
            1.18.2
            1.18.1
            1.18
            1.17.1
          java: 17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
