name: Release

on:
  push:
  workflow_dispatch:

jobs:
  build:

    if: "startsWith(github.event.head_commit.message, '🔼')"
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.4.1
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
          
    - name: Build artifacts
      run: ./gradlew build
      
    - uses: avakar/tag-and-release@v1
      with:
        tag_name: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        tag_name: ${{ github.sha }}
        artifacts: build/libs/*-all.jar
        name: Build ${{ github.sha }}
